name: Save version information
  shell: bash
  id: versioning
  run: |
    VERSION=`ls backend/build/libs/*.jar | cut -d "/" -f4 | cut -d - -f3,4`
    VERSION=${VERSION::-4}
    echo "Version: ${VERSION}"
    TIMESTAMP=`date +%s`
    cp backend/build/libs/*.jar ${VERSION}-${TIMESTAMP}.jar
    ls -la
    echo "::set-output name=VERSION::${VERSION}-${TIMESTAMP}"
  outputs:
    version:
