name: Deploy frontend to PROD

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy configuration
        shell: bash
        run: |
          cp frontend/src/main/configs/prod_config.js frontend/src/main/resources/js/config.js
      - name: Upload Frontend files via FTP to PROD
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://ftp.nethely.hu:21/
          ftp-username: ingazom.hu
          ftp-password: ${{ secrets.FTP_PASSWORD_PROD }}
          local-dir: frontend/src/main/resources/
          git-ftp-args: --insecure