name: Deploy frontend to DEV

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'integration/*'
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_dev.yml'
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy configuration
        shell: bash
        run: |
          cp frontend/src/main/configs/dev_config.js frontend/src/main/resources/js/config.js
      - name: Upload Frontend files via FTP to DEV
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://files.000webhost.com:21/public_html/
          ftp-username: dev-ingazom-hu
          ftp-password: ${{ secrets.FTP_PASSWORD_DEV }}
          local-dir: frontend/src/main/resources/
          git-ftp-args: --insecure