name: Deploy frontend

on:
  push:
    branches:
      - master
      - 'feature/new_env'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy configuration
        shell: bash
        run: |
          pwd

          cp frontend/src/main/configs/dev_config.js frontend/src/main/resources/js/config.js
          git add -f frontend/src/main/resources/js/config.js

          ls -la frontend/src/main/resources/js
      - name: Upload Frontend files via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://files.000webhost.com:21/public_html/
          ftp-username: dev-ingazom-hu
          ftp-password: ${{ secrets.FTP_PASSWORD_DEV }}
          local-dir: frontend/src/main/resources/
          git-ftp-args: --insecure -f