name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build test bootJar
    - name: Save version information
      shell: bash
      id: versioning
      run: |
        VERSION=`ls libs/*.jar | cut -d "/" -f2 | cut -d . -f1,2 | cut -d - -f2,3`
        cp libs/*.jar $VERSION.jar
        ls -la
        echo "::set-output name=VERSION::$VERSION"
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v5
      with:
        aws_access_key: ${{ secrets.aws_username }}
        aws_secret_key: ${{ secrets.aws_password }}
        application_name: Ingazom
        environment_name: Ingazom-env
        version_label: ${{ steps.versioning.outputs.VERSION }}
        region: us-west-3
        deployment_package: ${{ steps.versioning.outputs.VERSION }}.jar